"""empty message

Revision ID: 176e9bdfc958
Revises: 0a1de716fcd1
Create Date: 2024-06-11 09:05:22.298497

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '176e9bdfc958'
down_revision = '0a1de716fcd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_column('usuario_creacion')
        batch_op.drop_column('fecha_modificacion')
        batch_op.drop_column('usuario_modificacion')
        batch_op.drop_column('fecha_creacion')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_creacion', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True))
        batch_op.add_column(sa.Column('usuario_modificacion', mysql.VARCHAR(length=15), nullable=True))
        batch_op.add_column(sa.Column('fecha_modificacion', mysql.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('usuario_creacion', mysql.VARCHAR(length=15), nullable=True))

    # ### end Alembic commands ###
