"""ffff

Revision ID: 46c7e3e1ace2
Revises: 3cb4fc1332cf
Create Date: 2024-07-29 23:44:19.041273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46c7e3e1ace2'
down_revision = '3cb4fc1332cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('establecimiento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.Integer(), nullable=True))

    with op.batch_alter_table('puntosdeemision', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('puntosdeemision', schema=None) as batch_op:
        batch_op.drop_column('estado')

    with op.batch_alter_table('establecimiento', schema=None) as batch_op:
        batch_op.drop_column('estado')

    # ### end Alembic commands ###
