"""agregar codigos a productos

Revision ID: 5da652157e2f
Revises: e35d5aad3a81
Create Date: 2024-07-24 15:44:06.504309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5da652157e2f'
down_revision = 'e35d5aad3a81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Cod_Prod', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('Cod_Aux', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_column('Cod_Aux')
        batch_op.drop_column('Cod_Prod')

    # ### end Alembic commands ###
