"""empty message

Revision ID: 6e6600755d71
Revises: eebedd759739
Create Date: 2024-07-28 15:58:28.467672

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6e6600755d71'
down_revision = 'eebedd759739'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('establecimiento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=False),
    sa.Column('codigo_identificacion', sa.String(length=50), nullable=False),
    sa.Column('infraestructura', sa.Text(), nullable=True),
    sa.Column('horarios', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_identificacion')
    )
    op.create_table('punto_de_emision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=False),
    sa.Column('codigo_identificacion', sa.String(length=50), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('equipos', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_identificacion')
    )
    with op.batch_alter_table('cab_factura', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_cooperativa', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('id_responsable', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'usuarios', ['id_responsable'], ['id'])
        batch_op.create_foreign_key(None, 'cooperativas', ['id_cooperativa'], ['id_cooperativa'])
        batch_op.drop_column('telefono')
        batch_op.drop_column('apellido')
        batch_op.drop_column('direccion')
        batch_op.drop_column('cedula_o_ruc')
        batch_op.drop_column('nombre')
        batch_op.drop_column('id_vendedor')
        batch_op.drop_column('razon_social')

    with op.batch_alter_table('detalle_factura', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_producto', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'productos', ['id_producto'], ['id'])
        batch_op.drop_column('nombre_producto')
        batch_op.drop_column('cod_producto')
        batch_op.drop_column('fecha_fact')
        batch_op.drop_column('numero_factura')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detalle_factura', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numero_factura', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('fecha_fact', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('cod_producto', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('nombre_producto', mysql.VARCHAR(length=350), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_producto')

    with op.batch_alter_table('cab_factura', schema=None) as batch_op:
        batch_op.add_column(sa.Column('razon_social', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('id_vendedor', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('nombre', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('cedula_o_ruc', mysql.VARCHAR(length=13), nullable=True))
        batch_op.add_column(sa.Column('direccion', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('apellido', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('telefono', mysql.VARCHAR(length=10), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_responsable')
        batch_op.drop_column('id_cooperativa')

    op.drop_table('punto_de_emision')
    op.drop_table('establecimiento')
    # ### end Alembic commands ###
