"""ddddd

Revision ID: 6e76406db24e
Revises: 
Create Date: 2024-06-19 22:34:42.074446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e76406db24e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Auditorias',
    sa.Column('IdAuditoria', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=False),
    sa.Column('moduloAfectado', sa.String(length=255), nullable=False),
    sa.Column('detallesAdicional', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('IdAuditoria')
    )
    op.create_table('Categorías',
    sa.Column('Idcategoria', sa.Integer(), nullable=False),
    sa.Column('nombreCategoria', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('Idcategoria')
    )
    op.create_table('Cliente',
    sa.Column('IdCliente', sa.Integer(), nullable=False),
    sa.Column('NombreCliente', sa.String(length=255), nullable=False),
    sa.Column('ApellidoCliente', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=False),
    sa.Column('Telefono', sa.String(length=255), nullable=False),
    sa.Column('ciudad', sa.String(length=255), nullable=False),
    sa.Column('EstadoCliente', sa.Integer(), nullable=False),
    sa.Column('CodPostal', sa.String(length=255), nullable=False),
    sa.Column('Pais', sa.String(length=255), nullable=False),
    sa.Column('FechaNacimiento', sa.Date(), nullable=False),
    sa.Column('FechaRegistro', sa.Date(), nullable=False),
    sa.Column('FechaEliminacion', sa.Date(), nullable=True),
    sa.Column('RUCoCedula', sa.String(length=13), nullable=False),
    sa.PrimaryKeyConstraint('IdCliente')
    )
    op.create_table('Provincias',
    sa.Column('IdProvincia', sa.Integer(), nullable=False),
    sa.Column('NombreProvincia', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('IdProvincia')
    )
    op.create_table('Unidades',
    sa.Column('IdUnidad', sa.String(length=3), nullable=False),
    sa.Column('NombreConductor', sa.String(length=255), nullable=False),
    sa.Column('ApellidoConductor', sa.String(length=255), nullable=False),
    sa.Column('Descripcion', sa.String(length=500), nullable=False),
    sa.Column('EstadoUnidad', sa.String(length=80), nullable=False),
    sa.Column('Marca', sa.String(length=100), nullable=False),
    sa.Column('Modelo', sa.String(length=255), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('Matricula', sa.String(length=255), nullable=False),
    sa.Column('Color', sa.String(length=100), nullable=False),
    sa.Column('capacidad', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=False),
    sa.Column('FechaRegistro', sa.Date(), nullable=False),
    sa.Column('Usuariocreación', sa.String(length=100), nullable=False),
    sa.Column('FechaCreación', sa.Date(), nullable=False),
    sa.Column('Fechaeliminacion', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('IdUnidad')
    )
    op.create_table('categoria_producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('estado', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=False),
    sa.Column('usuario_creacion', sa.String(length=15), nullable=True),
    sa.Column('usuario_modificacion', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sucursal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigoSucursal', sa.String(length=100), nullable=True),
    sa.Column('direccionSucursal', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('AlquilerVehiculos',
    sa.Column('IdAlquiler', sa.Integer(), nullable=False),
    sa.Column('IdUnidad', sa.String(length=3), nullable=False),
    sa.Column('IdCliente', sa.Integer(), nullable=False),
    sa.Column('horaSalida', sa.Time(), nullable=False),
    sa.Column('horaLlegada', sa.Time(), nullable=False),
    sa.Column('FechaRecorrido', sa.DateTime(), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.Column('lugarOrigen', sa.String(length=200), nullable=False),
    sa.Column('lugarDestino', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['IdCliente'], ['Cliente.IdCliente'], ),
    sa.ForeignKeyConstraint(['IdUnidad'], ['Unidades.IdUnidad'], ),
    sa.PrimaryKeyConstraint('IdAlquiler')
    )
    op.create_table('Ciudades',
    sa.Column('IdCiudad', sa.Integer(), nullable=False),
    sa.Column('IdProvincia', sa.Integer(), nullable=False),
    sa.Column('NombreCiudad', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['IdProvincia'], ['Provincias.IdProvincia'], ),
    sa.PrimaryKeyConstraint('IdCiudad')
    )
    op.create_table('producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('precio', sa.Float(), nullable=True),
    sa.Column('estado', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria_producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('venta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=100), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('Sucursal', sa.Integer(), nullable=False),
    sa.Column('fecha_venta', sa.DateTime(), nullable=False),
    sa.Column('estado', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=False),
    sa.Column('usuario_creacion', sa.String(length=15), nullable=True),
    sa.Column('usuario_modificacion', sa.String(length=15), nullable=True),
    sa.ForeignKeyConstraint(['Sucursal'], ['sucursal.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['Cliente.IdCliente'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Destinos',
    sa.Column('IDestino', sa.Integer(), nullable=False),
    sa.Column('Ubicacion', sa.String(length=255), nullable=False),
    sa.Column('IdCiudad', sa.Integer(), nullable=False),
    sa.Column('IdProvincia', sa.Integer(), nullable=False),
    sa.Column('descripción', sa.String(length=255), nullable=False),
    sa.Column('Activo', sa.String(length=2), nullable=False),
    sa.Column('FechaCreación', sa.Date(), nullable=False),
    sa.Column('FechaModificacion', sa.Date(), nullable=True),
    sa.Column('FechaEliminacion', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['IdCiudad'], ['Ciudades.IdCiudad'], ),
    sa.ForeignKeyConstraint(['IdProvincia'], ['Provincias.IdProvincia'], ),
    sa.PrimaryKeyConstraint('IDestino')
    )
    op.create_table('venta_detalle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=False),
    sa.Column('usuario_creacion', sa.String(length=15), nullable=True),
    sa.Column('usuario_modificacion', sa.String(length=15), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['venta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Paquetes',
    sa.Column('IdPaquete', sa.Integer(), nullable=False),
    sa.Column('IdDestino', sa.Integer(), nullable=False),
    sa.Column('NombrePaquete', sa.String(length=255), nullable=False),
    sa.Column('EstadoPaquete', sa.String(length=20), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.Column('precio', sa.Numeric(), nullable=False),
    sa.Column('FechaInicio', sa.Date(), nullable=False),
    sa.Column('FechaFin', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['IdDestino'], ['Destinos.IDestino'], ),
    sa.PrimaryKeyConstraint('IdPaquete')
    )
    op.create_table('Reservas',
    sa.Column('IdReserva', sa.Integer(), nullable=False),
    sa.Column('IdCliente', sa.Integer(), nullable=False),
    sa.Column('IdDestino', sa.Integer(), nullable=False),
    sa.Column('IdUnidad', sa.String(length=3), nullable=False),
    sa.Column('FechahoraReserva', sa.DateTime(), nullable=False),
    sa.Column('estadoReserva', sa.String(length=30), nullable=False),
    sa.Column('detallesAdicional', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['IdCliente'], ['Cliente.IdCliente'], ),
    sa.ForeignKeyConstraint(['IdDestino'], ['Destinos.IDestino'], ),
    sa.ForeignKeyConstraint(['IdUnidad'], ['Unidades.IdUnidad'], ),
    sa.PrimaryKeyConstraint('IdReserva')
    )
    op.create_table('Viajes',
    sa.Column('IdViaje', sa.Integer(), nullable=False),
    sa.Column('IdUnidad', sa.String(length=3), nullable=False),
    sa.Column('IdDestino', sa.Integer(), nullable=False),
    sa.Column('IdCliente', sa.Integer(), nullable=False),
    sa.Column('horaTraslado', sa.Time(), nullable=False),
    sa.Column('FechaTraslado', sa.Date(), nullable=False),
    sa.Column('FechaCreación', sa.DateTime(), nullable=False),
    sa.Column('FechaEliminacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['IdCliente'], ['Cliente.IdCliente'], ),
    sa.ForeignKeyConstraint(['IdDestino'], ['Destinos.IDestino'], ),
    sa.ForeignKeyConstraint(['IdUnidad'], ['Unidades.IdUnidad'], ),
    sa.PrimaryKeyConstraint('IdViaje')
    )
    op.create_table('Calificaciones',
    sa.Column('IdCalificacion', sa.Integer(), nullable=False),
    sa.Column('IdCliente', sa.Integer(), nullable=False),
    sa.Column('IdViaje', sa.Integer(), nullable=False),
    sa.Column('puntuacion', sa.Integer(), nullable=False),
    sa.Column('comentarioTexto', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['IdCliente'], ['Cliente.IdCliente'], ),
    sa.ForeignKeyConstraint(['IdViaje'], ['Viajes.IdViaje'], ),
    sa.PrimaryKeyConstraint('IdCalificacion')
    )
    op.create_table('Comentarios',
    sa.Column('IdComentario', sa.Integer(), nullable=False),
    sa.Column('IdCliente', sa.Integer(), nullable=False),
    sa.Column('IdViaje', sa.Integer(), nullable=False),
    sa.Column('FechaRegistro', sa.DateTime(), nullable=False),
    sa.Column('textoComentario', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['IdCliente'], ['Cliente.IdCliente'], ),
    sa.ForeignKeyConstraint(['IdViaje'], ['Viajes.IdViaje'], ),
    sa.PrimaryKeyConstraint('IdComentario')
    )
    op.create_table('Itinerarios',
    sa.Column('IdItinerario', sa.Integer(), nullable=False),
    sa.Column('IdViaje', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['IdViaje'], ['Viajes.IdViaje'], ),
    sa.PrimaryKeyConstraint('IdItinerario')
    )
    op.create_table('Pagos',
    sa.Column('IdPago', sa.Integer(), nullable=False),
    sa.Column('IdReserva', sa.Integer(), nullable=False),
    sa.Column('metodoPago', sa.String(length=30), nullable=False),
    sa.Column('monto', sa.Numeric(), nullable=False),
    sa.Column('fechahoraPago', sa.DateTime(), nullable=False),
    sa.Column('estadoPago', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['IdReserva'], ['Reservas.IdReserva'], ),
    sa.PrimaryKeyConstraint('IdPago')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Pagos')
    op.drop_table('Itinerarios')
    op.drop_table('Comentarios')
    op.drop_table('Calificaciones')
    op.drop_table('Viajes')
    op.drop_table('Reservas')
    op.drop_table('Paquetes')
    op.drop_table('venta_detalle')
    op.drop_table('Destinos')
    op.drop_table('venta')
    op.drop_table('producto')
    op.drop_table('Ciudades')
    op.drop_table('AlquilerVehiculos')
    op.drop_table('user')
    op.drop_table('sucursal')
    op.drop_table('categoria_producto')
    op.drop_table('Unidades')
    op.drop_table('Provincias')
    op.drop_table('Cliente')
    op.drop_table('Categorías')
    op.drop_table('Auditorias')
    # ### end Alembic commands ###
