"""id_cooperativa agregado como clave foranea de conductores

Revision ID: 724083596b74
Revises: b648726037ac
Create Date: 2024-07-09 23:08:22.511624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '724083596b74'
down_revision = 'b648726037ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conductores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_cooperativa', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'cooperativas', ['id_cooperativa'], ['id_cooperativa'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conductores', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_cooperativa')

    # ### end Alembic commands ###
