"""ddddd

Revision ID: 9499c9e32a4c
Revises: 6e76406db24e
Create Date: 2024-06-19 22:52:53.230518

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9499c9e32a4c'
down_revision = '6e76406db24e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Auditorias',
    sa.Column('IdAuditoria', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=False),
    sa.Column('moduloAfectado', sa.String(length=255), nullable=False),
    sa.Column('detallesAdicional', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('IdAuditoria')
    )
    op.create_table('Categorías',
    sa.Column('Idcategoria', sa.Integer(), nullable=False),
    sa.Column('nombreCategoria', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('Idcategoria')
    )
    op.create_table('Cliente',
    sa.Column('IdCliente', sa.Integer(), nullable=False),
    sa.Column('NombreCliente', sa.String(length=255), nullable=False),
    sa.Column('ApellidoCliente', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=False),
    sa.Column('Telefono', sa.String(length=255), nullable=False),
    sa.Column('ciudad', sa.String(length=255), nullable=False),
    sa.Column('EstadoCliente', sa.Integer(), nullable=False),
    sa.Column('CodPostal', sa.String(length=255), nullable=False),
    sa.Column('Pais', sa.String(length=255), nullable=False),
    sa.Column('FechaNacimiento', sa.Date(), nullable=False),
    sa.Column('FechaRegistro', sa.Date(), nullable=False),
    sa.Column('FechaEliminacion', sa.Date(), nullable=True),
    sa.Column('RUCoCedula', sa.String(length=13), nullable=False),
    sa.PrimaryKeyConstraint('IdCliente')
    )
    op.create_table('Provincias',
    sa.Column('IdProvincia', sa.Integer(), nullable=False),
    sa.Column('NombreProvincia', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('IdProvincia')
    )
    op.create_table('Unidades',
    sa.Column('IdUnidad', sa.String(length=3), nullable=False),
    sa.Column('NombreConductor', sa.String(length=255), nullable=False),
    sa.Column('ApellidoConductor', sa.String(length=255), nullable=False),
    sa.Column('Descripcion', sa.String(length=500), nullable=False),
    sa.Column('EstadoUnidad', sa.String(length=80), nullable=False),
    sa.Column('Marca', sa.String(length=100), nullable=False),
    sa.Column('Modelo', sa.String(length=255), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('Matricula', sa.String(length=255), nullable=False),
    sa.Column('Color', sa.String(length=100), nullable=False),
    sa.Column('capacidad', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=False),
    sa.Column('FechaRegistro', sa.Date(), nullable=False),
    sa.Column('Usuariocreación', sa.String(length=100), nullable=False),
    sa.Column('FechaCreación', sa.Date(), nullable=False),
    sa.Column('Fechaeliminacion', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('IdUnidad')
    )
    op.create_table('AlquilerVehiculos',
    sa.Column('IdAlquiler', sa.Integer(), nullable=False),
    sa.Column('IdUnidad', sa.String(length=3), nullable=False),
    sa.Column('IdCliente', sa.Integer(), nullable=False),
    sa.Column('horaSalida', sa.Time(), nullable=False),
    sa.Column('horaLlegada', sa.Time(), nullable=False),
    sa.Column('FechaRecorrido', sa.DateTime(), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.Column('lugarOrigen', sa.String(length=200), nullable=False),
    sa.Column('lugarDestino', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['IdCliente'], ['Cliente.IdCliente'], ),
    sa.ForeignKeyConstraint(['IdUnidad'], ['Unidades.IdUnidad'], ),
    sa.PrimaryKeyConstraint('IdAlquiler')
    )
    op.create_table('Ciudades',
    sa.Column('IdCiudad', sa.Integer(), nullable=False),
    sa.Column('IdProvincia', sa.Integer(), nullable=False),
    sa.Column('NombreCiudad', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['IdProvincia'], ['Provincias.IdProvincia'], ),
    sa.PrimaryKeyConstraint('IdCiudad')
    )
    op.create_table('Destinos',
    sa.Column('IDestino', sa.Integer(), nullable=False),
    sa.Column('Ubicacion', sa.String(length=255), nullable=False),
    sa.Column('IdCiudad', sa.Integer(), nullable=False),
    sa.Column('IdProvincia', sa.Integer(), nullable=False),
    sa.Column('descripción', sa.String(length=255), nullable=False),
    sa.Column('Activo', sa.String(length=2), nullable=False),
    sa.Column('FechaCreación', sa.Date(), nullable=False),
    sa.Column('FechaModificacion', sa.Date(), nullable=True),
    sa.Column('FechaEliminacion', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['IdCiudad'], ['Ciudades.IdCiudad'], ),
    sa.ForeignKeyConstraint(['IdProvincia'], ['Provincias.IdProvincia'], ),
    sa.PrimaryKeyConstraint('IDestino')
    )
    op.create_table('Paquetes',
    sa.Column('IdPaquete', sa.Integer(), nullable=False),
    sa.Column('IdDestino', sa.Integer(), nullable=False),
    sa.Column('NombrePaquete', sa.String(length=255), nullable=False),
    sa.Column('EstadoPaquete', sa.String(length=20), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.Column('precio', sa.Numeric(), nullable=False),
    sa.Column('FechaInicio', sa.Date(), nullable=False),
    sa.Column('FechaFin', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['IdDestino'], ['Destinos.IDestino'], ),
    sa.PrimaryKeyConstraint('IdPaquete')
    )
    op.create_table('Reservas',
    sa.Column('IdReserva', sa.Integer(), nullable=False),
    sa.Column('IdCliente', sa.Integer(), nullable=False),
    sa.Column('IdDestino', sa.Integer(), nullable=False),
    sa.Column('IdUnidad', sa.String(length=3), nullable=False),
    sa.Column('FechahoraReserva', sa.DateTime(), nullable=False),
    sa.Column('estadoReserva', sa.String(length=30), nullable=False),
    sa.Column('detallesAdicional', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['IdCliente'], ['Cliente.IdCliente'], ),
    sa.ForeignKeyConstraint(['IdDestino'], ['Destinos.IDestino'], ),
    sa.ForeignKeyConstraint(['IdUnidad'], ['Unidades.IdUnidad'], ),
    sa.PrimaryKeyConstraint('IdReserva')
    )
    op.create_table('Viajes',
    sa.Column('IdViaje', sa.Integer(), nullable=False),
    sa.Column('IdUnidad', sa.String(length=3), nullable=False),
    sa.Column('IdDestino', sa.Integer(), nullable=False),
    sa.Column('IdCliente', sa.Integer(), nullable=False),
    sa.Column('horaTraslado', sa.Time(), nullable=False),
    sa.Column('FechaTraslado', sa.Date(), nullable=False),
    sa.Column('FechaCreación', sa.DateTime(), nullable=False),
    sa.Column('FechaEliminacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['IdCliente'], ['Cliente.IdCliente'], ),
    sa.ForeignKeyConstraint(['IdDestino'], ['Destinos.IDestino'], ),
    sa.ForeignKeyConstraint(['IdUnidad'], ['Unidades.IdUnidad'], ),
    sa.PrimaryKeyConstraint('IdViaje')
    )
    op.create_table('Calificaciones',
    sa.Column('IdCalificacion', sa.Integer(), nullable=False),
    sa.Column('IdCliente', sa.Integer(), nullable=False),
    sa.Column('IdViaje', sa.Integer(), nullable=False),
    sa.Column('puntuacion', sa.Integer(), nullable=False),
    sa.Column('comentarioTexto', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['IdCliente'], ['Cliente.IdCliente'], ),
    sa.ForeignKeyConstraint(['IdViaje'], ['Viajes.IdViaje'], ),
    sa.PrimaryKeyConstraint('IdCalificacion')
    )
    op.create_table('Comentarios',
    sa.Column('IdComentario', sa.Integer(), nullable=False),
    sa.Column('IdCliente', sa.Integer(), nullable=False),
    sa.Column('IdViaje', sa.Integer(), nullable=False),
    sa.Column('FechaRegistro', sa.DateTime(), nullable=False),
    sa.Column('textoComentario', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['IdCliente'], ['Cliente.IdCliente'], ),
    sa.ForeignKeyConstraint(['IdViaje'], ['Viajes.IdViaje'], ),
    sa.PrimaryKeyConstraint('IdComentario')
    )
    op.create_table('Itinerarios',
    sa.Column('IdItinerario', sa.Integer(), nullable=False),
    sa.Column('IdViaje', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['IdViaje'], ['Viajes.IdViaje'], ),
    sa.PrimaryKeyConstraint('IdItinerario')
    )
    op.create_table('Pagos',
    sa.Column('IdPago', sa.Integer(), nullable=False),
    sa.Column('IdReserva', sa.Integer(), nullable=False),
    sa.Column('metodoPago', sa.String(length=30), nullable=False),
    sa.Column('monto', sa.Numeric(), nullable=False),
    sa.Column('fechahoraPago', sa.DateTime(), nullable=False),
    sa.Column('estadoPago', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['IdReserva'], ['Reservas.IdReserva'], ),
    sa.PrimaryKeyConstraint('IdPago')
    )
    op.drop_table('ciudades')
    op.drop_table('auditorias')
    op.drop_table('reservas')
    op.drop_table('paquetes')
    op.drop_table('pagos')
    op.drop_table('provincias')
    op.drop_table('categorías')
    op.drop_table('viajes')
    op.drop_table('alquilervehiculos')
    op.drop_table('unidades')
    op.drop_table('cliente')
    op.drop_table('destinos')
    op.drop_table('itinerarios')
    op.drop_table('comentarios')
    op.drop_table('calificaciones')
    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.drop_constraint('venta_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'Cliente', ['cliente_id'], ['IdCliente'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('venta_ibfk_2', 'cliente', ['cliente_id'], ['IdCliente'])

    op.create_table('calificaciones',
    sa.Column('IdCalificacion', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('IdCliente', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('IdViaje', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('puntuacion', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('comentarioTexto', mysql.VARCHAR(length=500), nullable=False),
    sa.ForeignKeyConstraint(['IdCliente'], ['cliente.IdCliente'], name='calificaciones_ibfk_1'),
    sa.ForeignKeyConstraint(['IdViaje'], ['viajes.IdViaje'], name='calificaciones_ibfk_2'),
    sa.PrimaryKeyConstraint('IdCalificacion'),
    mariadb_collate='utf8mb4_general_ci',
    mariadb_default_charset='utf8mb4',
    mariadb_engine='InnoDB'
    )
    op.create_table('comentarios',
    sa.Column('IdComentario', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('IdCliente', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('IdViaje', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('FechaRegistro', mysql.DATETIME(), nullable=False),
    sa.Column('textoComentario', mysql.VARCHAR(length=500), nullable=False),
    sa.ForeignKeyConstraint(['IdCliente'], ['cliente.IdCliente'], name='comentarios_ibfk_1'),
    sa.ForeignKeyConstraint(['IdViaje'], ['viajes.IdViaje'], name='comentarios_ibfk_2'),
    sa.PrimaryKeyConstraint('IdComentario'),
    mariadb_collate='utf8mb4_general_ci',
    mariadb_default_charset='utf8mb4',
    mariadb_engine='InnoDB'
    )
    op.create_table('itinerarios',
    sa.Column('IdItinerario', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('IdViaje', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('descripcion', mysql.VARCHAR(length=500), nullable=False),
    sa.ForeignKeyConstraint(['IdViaje'], ['viajes.IdViaje'], name='itinerarios_ibfk_1'),
    sa.PrimaryKeyConstraint('IdItinerario'),
    mariadb_collate='utf8mb4_general_ci',
    mariadb_default_charset='utf8mb4',
    mariadb_engine='InnoDB'
    )
    op.create_table('destinos',
    sa.Column('IDestino', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('Ubicacion', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('IdCiudad', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('IdProvincia', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('descripción', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('Activo', mysql.VARCHAR(length=2), nullable=False),
    sa.Column('FechaCreación', sa.DATE(), nullable=False),
    sa.Column('FechaModificacion', sa.DATE(), nullable=True),
    sa.Column('FechaEliminacion', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['IdCiudad'], ['ciudades.IdCiudad'], name='destinos_ibfk_1'),
    sa.ForeignKeyConstraint(['IdProvincia'], ['provincias.IdProvincia'], name='destinos_ibfk_2'),
    sa.PrimaryKeyConstraint('IDestino'),
    mariadb_collate='utf8mb4_general_ci',
    mariadb_default_charset='utf8mb4',
    mariadb_engine='InnoDB'
    )
    op.create_table('cliente',
    sa.Column('IdCliente', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('NombreCliente', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('ApellidoCliente', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('direccion', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('Telefono', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('ciudad', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('EstadoCliente', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('CodPostal', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('Pais', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('FechaNacimiento', sa.DATE(), nullable=False),
    sa.Column('FechaRegistro', sa.DATE(), nullable=False),
    sa.Column('FechaEliminacion', sa.DATE(), nullable=True),
    sa.Column('RUCoCedula', mysql.VARCHAR(length=13), nullable=False),
    sa.PrimaryKeyConstraint('IdCliente'),
    mariadb_collate='utf8mb4_general_ci',
    mariadb_default_charset='utf8mb4',
    mariadb_engine='InnoDB'
    )
    op.create_table('unidades',
    sa.Column('IdUnidad', mysql.VARCHAR(length=3), nullable=False),
    sa.Column('NombreConductor', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('ApellidoConductor', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('Descripcion', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('EstadoUnidad', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('Marca', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('Modelo', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('ano', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('Matricula', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('Color', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('capacidad', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('tipo', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('FechaRegistro', sa.DATE(), nullable=False),
    sa.Column('Usuariocreación', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('FechaCreación', sa.DATE(), nullable=False),
    sa.Column('Fechaeliminacion', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('IdUnidad'),
    mariadb_collate='utf8mb4_general_ci',
    mariadb_default_charset='utf8mb4',
    mariadb_engine='InnoDB'
    )
    op.create_table('alquilervehiculos',
    sa.Column('IdAlquiler', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('IdUnidad', mysql.VARCHAR(length=3), nullable=False),
    sa.Column('IdCliente', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('horaSalida', mysql.TIME(), nullable=False),
    sa.Column('horaLlegada', mysql.TIME(), nullable=False),
    sa.Column('FechaRecorrido', mysql.DATETIME(), nullable=False),
    sa.Column('descripcion', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('lugarOrigen', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('lugarDestino', mysql.VARCHAR(length=200), nullable=False),
    sa.ForeignKeyConstraint(['IdCliente'], ['cliente.IdCliente'], name='alquilervehiculos_ibfk_1'),
    sa.ForeignKeyConstraint(['IdUnidad'], ['unidades.IdUnidad'], name='alquilervehiculos_ibfk_2'),
    sa.PrimaryKeyConstraint('IdAlquiler'),
    mariadb_collate='utf8mb4_general_ci',
    mariadb_default_charset='utf8mb4',
    mariadb_engine='InnoDB'
    )
    op.create_table('viajes',
    sa.Column('IdViaje', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('IdUnidad', mysql.VARCHAR(length=3), nullable=False),
    sa.Column('IdDestino', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('IdCliente', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('horaTraslado', mysql.TIME(), nullable=False),
    sa.Column('FechaTraslado', sa.DATE(), nullable=False),
    sa.Column('FechaCreación', mysql.DATETIME(), nullable=False),
    sa.Column('FechaEliminacion', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['IdCliente'], ['cliente.IdCliente'], name='viajes_ibfk_1'),
    sa.ForeignKeyConstraint(['IdDestino'], ['destinos.IDestino'], name='viajes_ibfk_2'),
    sa.ForeignKeyConstraint(['IdUnidad'], ['unidades.IdUnidad'], name='viajes_ibfk_3'),
    sa.PrimaryKeyConstraint('IdViaje'),
    mariadb_collate='utf8mb4_general_ci',
    mariadb_default_charset='utf8mb4',
    mariadb_engine='InnoDB'
    )
    op.create_table('categorías',
    sa.Column('Idcategoria', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nombreCategoria', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('Idcategoria'),
    mariadb_collate='utf8mb4_general_ci',
    mariadb_default_charset='utf8mb4',
    mariadb_engine='InnoDB'
    )
    op.create_table('provincias',
    sa.Column('IdProvincia', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('NombreProvincia', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('IdProvincia'),
    mariadb_collate='utf8mb4_general_ci',
    mariadb_default_charset='utf8mb4',
    mariadb_engine='InnoDB'
    )
    op.create_table('pagos',
    sa.Column('IdPago', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('IdReserva', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('metodoPago', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('monto', mysql.DECIMAL(precision=10, scale=0), nullable=False),
    sa.Column('fechahoraPago', mysql.DATETIME(), nullable=False),
    sa.Column('estadoPago', mysql.VARCHAR(length=30), nullable=False),
    sa.ForeignKeyConstraint(['IdReserva'], ['reservas.IdReserva'], name='pagos_ibfk_1'),
    sa.PrimaryKeyConstraint('IdPago'),
    mariadb_collate='utf8mb4_general_ci',
    mariadb_default_charset='utf8mb4',
    mariadb_engine='InnoDB'
    )
    op.create_table('paquetes',
    sa.Column('IdPaquete', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('IdDestino', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('NombrePaquete', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('EstadoPaquete', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('descripcion', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('precio', mysql.DECIMAL(precision=10, scale=0), nullable=False),
    sa.Column('FechaInicio', sa.DATE(), nullable=False),
    sa.Column('FechaFin', sa.DATE(), nullable=False),
    sa.ForeignKeyConstraint(['IdDestino'], ['destinos.IDestino'], name='paquetes_ibfk_1'),
    sa.PrimaryKeyConstraint('IdPaquete'),
    mariadb_collate='utf8mb4_general_ci',
    mariadb_default_charset='utf8mb4',
    mariadb_engine='InnoDB'
    )
    op.create_table('reservas',
    sa.Column('IdReserva', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('IdCliente', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('IdDestino', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('IdUnidad', mysql.VARCHAR(length=3), nullable=False),
    sa.Column('FechahoraReserva', mysql.DATETIME(), nullable=False),
    sa.Column('estadoReserva', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('detallesAdicional', mysql.VARCHAR(length=500), nullable=False),
    sa.ForeignKeyConstraint(['IdCliente'], ['cliente.IdCliente'], name='reservas_ibfk_1'),
    sa.ForeignKeyConstraint(['IdDestino'], ['destinos.IDestino'], name='reservas_ibfk_2'),
    sa.ForeignKeyConstraint(['IdUnidad'], ['unidades.IdUnidad'], name='reservas_ibfk_3'),
    sa.PrimaryKeyConstraint('IdReserva'),
    mariadb_collate='utf8mb4_general_ci',
    mariadb_default_charset='utf8mb4',
    mariadb_engine='InnoDB'
    )
    op.create_table('auditorias',
    sa.Column('IdAuditoria', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('tipo', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('moduloAfectado', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('detallesAdicional', mysql.VARCHAR(length=500), nullable=False),
    sa.PrimaryKeyConstraint('IdAuditoria'),
    mariadb_collate='utf8mb4_general_ci',
    mariadb_default_charset='utf8mb4',
    mariadb_engine='InnoDB'
    )
    op.create_table('ciudades',
    sa.Column('IdCiudad', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('IdProvincia', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('NombreCiudad', mysql.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['IdProvincia'], ['provincias.IdProvincia'], name='ciudades_ibfk_1'),
    sa.PrimaryKeyConstraint('IdCiudad'),
    mariadb_collate='utf8mb4_general_ci',
    mariadb_default_charset='utf8mb4',
    mariadb_engine='InnoDB'
    )
    op.drop_table('Pagos')
    op.drop_table('Itinerarios')
    op.drop_table('Comentarios')
    op.drop_table('Calificaciones')
    op.drop_table('Viajes')
    op.drop_table('Reservas')
    op.drop_table('Paquetes')
    op.drop_table('Destinos')
    op.drop_table('Ciudades')
    op.drop_table('AlquilerVehiculos')
    op.drop_table('Unidades')
    op.drop_table('Provincias')
    op.drop_table('Cliente')
    op.drop_table('Categorías')
    op.drop_table('Auditorias')
    # ### end Alembic commands ###
