"""agrego el apellido

Revision ID: b648726037ac
Revises: 9c64e753d165
Create Date: 2024-07-09 22:30:10.072077

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b648726037ac'
down_revision = '9c64e753d165'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conductores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apellido', sa.String(length=100), nullable=False))
        batch_op.alter_column('nombre',
               existing_type=mysql.VARCHAR(collation='utf8mb3_spanish_ci', length=80),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conductores', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(collation='utf8mb3_spanish_ci', length=80),
               existing_nullable=False)
        batch_op.drop_column('apellido')

    # ### end Alembic commands ###
