"""jjjjj

Revision ID: d3a4ff81098d
Revises: ed99c230c52c
Create Date: 2024-07-20 22:48:54.846091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3a4ff81098d'
down_revision = 'ed99c230c52c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('boletos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_ruta', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('id_detalle', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('codigo', sa.String(length=255), nullable=True))
        batch_op.create_foreign_key(None, 'detalle_factura', ['id_detalle'], ['id_detalle'])
        batch_op.create_foreign_key(None, 'rutas', ['id_ruta'], ['id_ruta'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('boletos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('codigo')
        batch_op.drop_column('id_detalle')
        batch_op.drop_column('id_ruta')

    # ### end Alembic commands ###
