"""add campo descripcion en producto

Revision ID: fda734247caf
Revises: c62e1307c3f6
Create Date: 2024-07-23 00:29:02.849901

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fda734247caf'
down_revision = 'c62e1307c3f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medodosPago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('estado', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_eliminacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('medodospago')
    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.drop_constraint('pagos_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'medodosPago', ['id_metodo'], ['id'])

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_column('descripcion')

    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('pagos_ibfk_1', 'medodospago', ['id_metodo'], ['id'])

    op.create_table('medodospago',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(collation='utf8mb3_bin', length=100), nullable=True),
    sa.Column('descripcion', mysql.TEXT(collation='utf8mb3_bin'), nullable=True),
    sa.Column('estado', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('fecha_creacion', mysql.DATETIME(), nullable=True),
    sa.Column('fecha_eliminacion', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mariadb_collate='utf8mb3_bin',
    mariadb_default_charset='utf8mb3',
    mariadb_engine='InnoDB'
    )
    op.drop_table('medodosPago')
    # ### end Alembic commands ###
